# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Oh My Zsh plugins
default=(git
    aliases
    archlinux
    debian
    docker
    docker-compose
    rails
    ruby
    copybuffer
)
custom=(mg
)
final=(zsh-syntax-highlighting # Plugins that need to be at the very end of the array
)

plugins=("${default[@]}" "${custom[@]}"  "${final[@]}")


# Starts Oh My Zsh
source $ZSH/oh-my-zsh.sh
# Spaceship prompt
source "$HOME/.zsh/spaceship/spaceship.zsh"
