# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Oh My ZSH theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Oh My Zsh plugins
default=(git
    aliases
    alias-finder
    archlinux
    debian
    docker
    docker-compose
    rails
    ruby
    copybuffer
    direnv
)
custom=(mg
)
final=(zsh-syntax-highlighting # Plugins that need to be at the very end of the array
)

plugins=("${default[@]}" "${custom[@]}"  "${final[@]}")


# Starts Oh My Zsh
source $ZSH/oh-my-zsh.sh
